### PR TITLE
New Logo

### LINKED ISSUE #32: Design a good looking icon for the project
A lock won't work for long.

image

### PR DESCRIPTION
**Pull request by shivangswain**
Added the new logo and added a few return lines.

Resolves #32

### CODE REVIEW

**Comment by t0xic0der** [comment]
@VaibhavSaini19 @s-katte @sachin2912 could you guys please review this PR? Thanks in advance.

**Comment by s-katte** [comment]
> @VaibhavSaini19 @s-katte @sachin2912 could you guys please review this PR? Thanks in advance.

Sure.

@shivangswain can you please add the screenshot here for reference.

**Review by s-katte — CHANGES_REQUESTED** [review]
As these PR deals with adding of a new logo, all the changes apart from the logo are requested to revert back :
- adding of extra blank lines in ```back.py```
- swapping lines of import in ```main.py```
- deletion of ```cpu_affinity``` in ```back.py```

**Review by VaibhavSaini19 — APPROVED** [review]
Looks good to me

**Comment by shivangswain** [comment]
What exactly are we waiting for, peeps? CC: @t0xic0der & @s-katte

**Comment by s-katte** [comment]
> What exactly are we waiting for, peeps? CC: @t0xic0der & @s-katte

Changes are already approved, @t0xic0der has to merge them.

**Review by t0xic0der — APPROVED** [review]
Nice work with putting the PEP8 compliance in `back.py` and `main.py`.

We have already approved the logo so no comments there.

**Comment by t0xic0der** [comment]
> As this PR deals with adding of a new logo, all the changes apart from the logo are requested to revert back :
> 
>     * deletion of `cpu_affinity` in `back.py`

Thanks for marking them out. @s-katte

**Pull request merged**
